### ISSUE TITLE
Update the README.md to include the new IPU6 driver stack (and potentially not requiring any workarounds for the camera) since kernel 6.10 stable has been released 

### ISSUE THREAD

**Issue by n3thshan** [aigilea/hp_spectre_x360_14_eu0xxx#15]

**Comment by alexstore06** [comment]
How do you get this working? I'm on kernel 6.10 and the Fedora 41 Beta, so all the right components should be set up, but I can't find a way to test it. Firefox pipewire camera support seems to still be broken, and cheese crashes right out of the gate. 

I don't mind waiting for applications to support it, but I'd like to have at least one to test it with now.

**Comment by n3thshan** [comment]
The following sources might help you:

https://bugzilla.redhat.com/show_bug.cgi?id=2300336

https://fedoraproject.org/wiki/Changes/IPU6_Camera_support#Upgrade/compatibility_impact

https://jgrulich.cz/tag/pipewire/

**Comment by nuclearforg** [comment]
According to Hans de Goede, there is some more work to get things working on Meteor Lake ([source](https://hansdegoede.dreamwidth.org/28841.html)). While upstream `libcamera` works out of the box, the `ov08x40` patch is still needed to power up the sensor.

**Comment by n3thshan** [comment]
its atleast glad to know that camera work is being done and in a couple of months hopefully we might not need any patch at all

**Comment by cdekort** [comment]
As of 6.11.0 release, I assume the patch is still required? Just upgraded, but no success on the camera yet.

**Comment by alexstore06** [comment]
I talked with Hans de Goede about this issue, and after a few test kernels, he narrowed it down to lack of support for a "Lattice MIPI aggregator" chip. He opened an associated issue on Intel's IPU6 drivers repo today. His comment about Meteor Lake on his blog post seemed to be more related to integrating the whole pipeline in Fedora on Meteor Lake laptops - he didn't mention it in our communication.

https://github.com/intel/ipu6-drivers/issues/281

**Comment by n3thshan** [comment]
this is great news!

**Comment by n3thshan** [comment]
hi. im wondering whats the progress on this. seems like its stagnant in the ipu6-drivers repo at least @alexstore06.

**Comment by alexstore06** [comment]
The Lattice MIPI aggregator chip does not actually seem to be present in this laptop. Hans de Goede has continued to build new Fedora test kernels to get the camera working, but we haven't had any luck so far. I believe he expects to get another test kernel ready by early next week with his latest theory implemented, but he's just about out of ideas at this point.

If you'd like to work on this issue, make sure that you've followed the instructions [here](https://fedoraproject.org/wiki/Changes/IPU6_Camera_support#How_To_Test) under "How to Test." You can then install the new kernel from [here](https://koji.fedoraproject.org/koji/taskinfo?taskID=125591567) using [these instructions](https://fedorapeople.org/~jwrdegoede/kernel-test-instructions.txt).

Use ```qcam``` for testing. ```dmesg``` will give you more information to work with.

**Comment by n3thshan** [comment]
i am more than willing to help contribute by reporting any logs, etc... thanks for the info.

**Comment by n3thshan** [comment]
i am more than willing to help contribute by reporting any logs, etc... thanks for the info. but please let us know whether his new hypothesis is gonna work or not next week. i am currently on fedora silverblue/universal blue so i am faced with the challenge of using the said kernels along with installing the required dependencies. allow me some time before i figure how to do it. thanks!

**Comment by n3thshan** [comment]
hello @alexstore06! im sorry i was busy these couple of weeks and was not able to test the kernel. I hope Hans has not given up yet right?
