### ISSUE TITLE
Touchpad palm rejection doesn't work

### ISSUE THREAD

**Issue by jmole** [aigilea/hp_spectre_x360_14_eu0xxx#6]
I think there is more work to be done here, because the touchpad actually has a lot of really cool features, including per-finger pressure reports.

But a quick way to get palm rejection working (at least for 16" model, ELAN device may be different for 14"):
```
echo 4160 | sudo tee $(find /sys/devices/ | grep ELAN07CE.*quirks)
```

**Comment by aigilea** [comment]
Thanks, it works on 14 as well, the only difference is device name.

`echo 4160 | sudo tee $(find /sys/devices/ | grep ELAN07CD.\*quirks)`

**Comment by jmole** [comment]
@aigilea any chance you could send me the VID/PID of the touchpad for the 14" model?

The output of this will have it:
`find /sys/devices/ | grep i2c-ELAN07C.*quirks`

**Comment by CppBaddy** [comment]
> @aigilea any chance you could send me the VID/PID of the touchpad for the 14" model?
> 
> The output of this will have it: `find /sys/devices/ | grep i2c-ELAN07C.*quirks`

/sys/devices/pci0000:00/0000:00:15.0/i2c_designware.0/i2c-0/i2c-ELAN07CD:00/0018:04F3:310A.0001/quirks

**Comment by jmole** [comment]
@CppBaddy thanks - I realized that setting the "right" quirks will not work if you try to do it after the module is loaded, so I submitted a [kernel patch](https://lore.kernel.org/linux-input/20240429070950.247183-1-jon@moeller.io/T/#u) to fix the issue properly - for some reason the github UI isn't letting me upload the patch file here, but I will send a MR later.

**Comment by CppBaddy** [comment]
@jmole Thank you for taking care. I really love this new gen laptop.

**Comment by n3thshan** [comment]
> @CppBaddy thanks - I realized that setting the "right" quirks will not work if you try to do it after the module is loaded, so I submitted a [kernel patch](https://lore.kernel.org/linux-input/20240429070950.247183-1-jon@moeller.io/T/#u) to fix the issue properly - for some reason the github UI isn't letting me upload the patch file here, but I will send a MR later.

hi did they accept it? also im planning to use the service on an immutable desktop with write access in /etc. will this work?

**Comment by jmole** [comment]
No, unfortunately it was just ignored since I posted it to the listserv instead of emailing a maintainer directly. I need to get it back on the radar just haven't had time.

**Comment by n3thshan** [comment]
please do so. thanks btw for ur support on this repo. i believe that @aigilea has abandoned the repo. maybe im wrong. if so it would be great if you could fork this and create a new one that is more concise and comprehensive to new spectre users?
